<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <name>${project.groupId}:${project.artifactId}</name>
    <url>https://github.com/jme-admin-ch/jme-object-storage-example/tree/main</url>
    <scm>
        <url>https://github.com/jme-admin-ch/jme-object-storage-example/tree/master.git</url>
        <connection>scm:git:git://github.com/jme-admin-ch/jme-object-storage-example.git</connection>
        <developerConnection>scm:git:ssh://github.com:jme-admin-ch/jme-object-storage-example.git</developerConnection>
    </scm>
    <developers>
        <developer>
            <name>BIT</name>
            <email>jeap-community@bit.admin.ch</email>
            <organization>Federal Office of Information Technology, Systems and Telecommunication FOITT</organization>
            <organizationUrl>https://www.bit.admin.ch/</organizationUrl>
        </developer>
    </developers>

    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0</url>
        </license>
    </licenses>

    <parent>
        <groupId>ch.admin.bit.jeap</groupId>
        <artifactId>jeap-spring-boot-parent</artifactId>
        <version>40.5.1</version>
        <relativePath/>
    </parent>

    <artifactId>jme-object-storage-example</artifactId>
    <version>5.5.1-SNAPSHOT</version>
    <packaging>jar</packaging>

    <properties>
        <jme-spring-boot-integration-test.version>6.2.0</jme-spring-boot-integration-test.version>
        <maven.javadoc.skip>false</maven.javadoc.skip>
    </properties>

    <dependencies>
        <dependency>
            <groupId>ch.admin.bit.jeap</groupId>
            <artifactId>jeap-spring-boot-object-storage-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc</artifactId>
        </dependency>

        <dependency>
            <groupId>ch.admin.bit.jeap</groupId>
            <artifactId>jeap-open-api-publisher-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>ch.admin.bit.jeap</groupId>
            <artifactId>jeap-spring-boot-swagger-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>ch.admin.bit.jeap</groupId>
            <artifactId>jeap-spring-boot-monitoring-starter</artifactId>
        </dependency>

        <!-- Testing -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>ch.admin.bit.jeap.jme</groupId>
            <artifactId>jme-spring-boot-integration-test</artifactId>
            <version>${jme-spring-boot-integration-test.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!-- Add license entry to jar manifest -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifestEntries>
                            <Bundle-License>https://www.apache.org/licenses/LICENSE-2.0</Bundle-License>
                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>
            <!-- Check third-party license compliance -->
            <plugin>
                <groupId>org.honton.chas</groupId>
                <artifactId>license-maven-plugin</artifactId>
            </plugin>
            <!-- Generate third-party license list -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>license-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>ch.admin.bit.jeap.jme.objectstorage.ObjectStorageExampleApplication</mainClass>
                </configuration>
                <executions>
                    <execution>
                        <!-- Skip repackaging to avoid building a fat jar -->
                        <phase>none</phase>
                    </execution>
                    <execution>
                        <id>spring-boot</id>
                        <goals>
                            <goal>build-info</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
